function nied_statList = import_nied_statList(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   nied_statList = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   nied_statList = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   nied_statList =
%   importfile('NIED_SeismicStation_20151119.csv', 1, 880);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/11/24 20:59:43

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,8,9,10,11,12,13,14,16]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,8,9,10,11,12,13,14,16]);
rawCellColumns = raw(:, [3,4,5,6,7,15]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
nied_statList = table;
nied_statList.VarName1  = cell2mat(rawNumericColumns(:, 1));
nied_statList.VarName2  = cell2mat(rawNumericColumns(:, 2));
nied_statList.hiStName  = rawCellColumns(:, 1);
nied_statList.VarName6  = rawCellColumns(:, 4);
nied_statList.lat1      = cell2mat(rawNumericColumns(:, 3));
nied_statList.lon1      = cell2mat(rawNumericColumns(:, 4));
nied_statList.lat2      = cell2mat(rawNumericColumns(:, 5));
nied_statList.lon2      = cell2mat(rawNumericColumns(:, 6));
nied_statList.VarName12 = cell2mat(rawNumericColumns(:, 7));
nied_statList.VarName13 = cell2mat(rawNumericColumns(:, 8));
nied_statList.VarName14 = cell2mat(rawNumericColumns(:, 9));
nied_statList.kikStName = rawCellColumns(:, 6);
nied_statList.VarName16 = cell2mat(rawNumericColumns(:, 10));