function [ctlg] = import_NCAeqDD(fileFullName)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /scratch/memeier/data/nocal/waldhauser/NCAeqDD.v201112.1.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/02/02 05:05:46

%% Initialize variables.
formatSpec   = '%4f%3f%3f%3f%3f%7f%12f%13f%9f%8f%8f%4f%8f%5f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(fileFullName,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
ctlg.yr  = dataArray{:, 1};
ctlg.mt  = dataArray{:, 2};
ctlg.dy  = dataArray{:, 3};
ctlg.hr  = dataArray{:, 4};
ctlg.min = dataArray{:, 5};
ctlg.sec = dataArray{:, 6};
ctlg.lat = dataArray{:, 7};
ctlg.lon = dataArray{:, 8};
ctlg.dep = dataArray{:, 9};
ctlg.eh1 = dataArray{:, 10};
ctlg.eh2 = dataArray{:, 11};
ctlg.az  = dataArray{:, 12};
ctlg.ez  = dataArray{:, 13};
ctlg.m   = dataArray{:, 14};
ctlg.id  = dataArray{:, 15};

%% Clear temporary variables
clearvars fileFullName formatSpec fileID dataArray ans;