function [triggerList] = import_SAFOD_PH_triggerList(listFullName) 
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /scratch/memeier/data/safod/PH_triggers.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/02/02 19:23:12

%% Initialize variables.
delimiter = {'\t',',',' '};

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: double (%f)
%	column6: text (%s)
%   column7: text (%s)
%	column8: double (%f)
%   column9: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%s%s%f%s%s%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(listFullName,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
%triggerList = table(dataArray{1:end-1}, 'VariableNames', {'trigID','VarName2','VarName3','VarName4','startDate','startTime','VarName7','endDate','endTime'});
triggerList = table(dataArray{[1,5,6,8,9]}, 'VariableNames', {'trigID','startDate','startTime','endDate','endTime'});
%% Clear temporary variables
clearvars listFullName delimiter formatSpec fileID dataArray ans;